/** Converte o cliente em `inicial` para o `<ClienteForm />`. */
export function clienteParaFormInicial(c: any) {
  return {
    id: c.id,
    tipo_pessoa: c.tipo_pessoa,
    nome: c.nome,
    documento: c.documento,
    documento_secundario: c.documento_secundario ?? "",
    data_nascimento: c.data_nascimento ?? "",
    estado_civil: c.estado_civil ?? "solteiro",
    regime_casamento: c.regime_casamento ?? "",
    mae: c.mae ?? "",
    pai: c.pai ?? "",
    sexo: c.sexo ?? "",
    nacionalidade: c.nacionalidade ?? "",
    naturalidade: c.naturalidade ?? "",
    tipo_documento_identidade: c.tipo_documento_identidade ?? "",
    numero_documento: c.numero_documento ?? "",
    orgao_expedidor: c.orgao_expedidor ?? "",
    uf_expedicao: c.uf_expedicao ?? "",
    data_expedicao: c.data_expedicao ?? "",
    profissao: c.profissao ?? "",
    empresa: c.empresa ?? "",
    banco_conta: c.banco_conta ?? "",
    agencia: c.agencia ?? "",
    conta_corrente: c.conta_corrente ?? "",
    digito_conta: c.digito_conta ?? "",
    email: c.email ?? "",
    telefone_celular: c.telefone_celular ?? "",
    renda_total_declarada: c.renda_total_declarada != null ? String(c.renda_total_declarada) : "",
    uf_interesse: c.uf_interesse ?? "",
    utiliza_fgts: c.utiliza_fgts ?? false,
    fg_autorizacao_dados: c.fg_autorizacao_dados ?? false,
    origem: c.origem,
    conjuge_nome: c.conjuge_nome ?? "",
    conjuge_cpf: c.conjuge_cpf ?? "",
    conjuge_data_nascimento: c.conjuge_data_nascimento ?? "",
    conjuge_nome_mae: c.conjuge_nome_mae ?? "",
    conjuge_sexo: c.conjuge_sexo ?? "",
    conjuge_nacionalidade: c.conjuge_nacionalidade ?? "",
    conjuge_tipo_documento_identidade: c.conjuge_tipo_documento_identidade ?? "",
    conjuge_numero_documento: c.conjuge_numero_documento ?? "",
    conjuge_orgao_expedidor: c.conjuge_orgao_expedidor ?? "",
    conjuge_uf_expedicao: c.conjuge_uf_expedicao ?? "",
    conjuge_data_expedicao: c.conjuge_data_expedicao ?? "",
    conjuge_profissao: c.conjuge_profissao ?? "",
    conjuge_empresa: c.conjuge_empresa ?? "",
    conjuge_renda: c.conjuge_renda != null ? String(c.conjuge_renda) : "",
    conjuge_email: c.conjuge_email ?? "",
    conjuge_celular: c.conjuge_celular ?? "",
    conjuge_banco_conta: c.conjuge_banco_conta ?? "",
    conjuge_agencia: c.conjuge_agencia ?? "",
    conjuge_conta_corrente: c.conjuge_conta_corrente ?? "",
    conjuge_digito_conta: c.conjuge_digito_conta ?? "",
  };
}
